### ISSUE TITLE
Wrong executable path

### ISSUE THREAD

**Issue by nvartolomei** [mitchellh/osext#1]
Hello,

I saw a bug in `executable` function from `osext_sysctl.go`, it will give wrong path if executable is run from another directory by using relative path like `../some_executable`. However it works if run like `./../some_executable`.

This change should fix the issue.

```
func executable() (string, error) {
    if getwdError != nil {
        return string(buf), getwdError
    } else {
-       if buf[0] == '.' {
+       if buf[0] == '.' && buf[1] == '/' {
            buf = buf[1:]
        }
    if startUpcwd[len(startUpcwd)-1] != '/' {
```

Also I noticed upstream has some other changes too, maybe it's a good idea to update this repo?

Should I create a pull-request for above change?

**Comment by mitchellh** [comment]
I think we should just move to upstream. I hear that they moved to GitHub now so maybe we can just switch to the actual lib. 

https://github.com/kardianos/osext
